baseURL = 'https://nohawrites.com/'
languageCode = 'en-us'
title = 'Noha Writes'
theme = 'PaperMod'

canonifyURLs = false
relativeURLs = true

[pagination]
  pagerSize = 5


[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"
  mainSections = ["blog"]
  showRecentPosts = true
  hideMeta = true
  customCSS = ["css/custom.css"]
  env = "production"

[params.profileMode]
  enabled = true
  title = "Noha Writes"
  subtitle = "Cybersecurity Enthusiast and Freelance Writer"
  imageUrl = "/images/profile.jpg"
  imageTitle = "Noha"
  imageWidth = 150
  imageHeight = 150


[[params.profileMode.buttons]]
name = "Read My Blog"
url = "/blog/"

[[params.profileMode.buttons]]
name = "Work With Me"
url = "/work-with-me/"

[params.assets]
  disableFingerprinting = true

[menu]

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 1

  [[menu.main]]
    name = "Work With Me"
    url = "/work-with-me/"
    weight = 2
